export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_FUTURE_WEATHER = 'FETCH_FUTURE_WEATHER';
export const FETCH_FUTURE_WEATHER_SUCCESS = 'FETCH_FUTURE_WEATHER_SUCCESS';
export const SET_WEATHER_UNITS = 'SET_WEATHER_UNITS';
